baseurl = "https://brk3.github.io/"
languageCode = "en-us"
title = "brk3.github.io"

theme = "nofancy"

[author]
    name = "Paul Bourke"
    github = "brk3"
    linkedin = "paul-bourke-0678052a"
    gaID = "UA-37886611-1"
    twitter = "brk3"
